### PR TITLE
docs: update README.md

### LINKED ISSUE #7: Draft README
Draft README and devpost.

### PR DESCRIPTION
**Pull request by Diaga**
Update ReadMe.md with project description, usage and available commands.  

fix #7

### CODE REVIEW

**Comment by wei** [comment]
Do we want to add:
- Authors
- Screenshots

**Comment by Diaga** [comment]
I am in favor of screenshots 👍 . On it!

**Comment by wei** [comment]
@Diaga @khattakdev 

The following images are hosted on GitHub (You can upload more by dragging them into the comment box)

**Urls:**
```
<img width="550" alt="sub" src="https://user-images.githubusercontent.com/5880908/99809301-18c58100-2b10-11eb-852a-46b52afce8de.png">
<img width="380" alt="card-created" src="https://user-images.githubusercontent.com/5880908/99809315-1bc07180-2b10-11eb-8533-b8b2aedd6bb8.png">
<img width="380" alt="card-moved" src="https://user-images.githubusercontent.com/5880908/99809319-1c590800-2b10-11eb-81d2-13e70d39e5cb.png">
<img width="380" alt="card-deleted" src="https://user-images.githubusercontent.com/5880908/99809316-1bc07180-2b10-11eb-928b-9fc0833820ee.png">
<img width="480" alt="card-edited" src="https://user-images.githubusercontent.com/5880908/99809318-1bc07180-2b10-11eb-97ad-cbbd2c9b4c71.png">
```

sub
card-created
card-moved
card-deleted
card-edited

**Review by khattakdev — APPROVED** [review]
Looks Good!

**Pull request merged**
